doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "username"
    password: "password"
    dbname: "database"
    host: "localhost"
user:
  john:
    working-hours-per-week: 40
    holidays-per-year: 28
    personnel-costs: 2500
  jane:
    aliases: [nick]
    working-hours-per-week: 26
    holidays-per-year: 25
    personnel-costs: 2400
general:
  timezone: "Europe/Berlin"
toggl:
  apiKey: "8ebaedbfb2b5724cb537fdb5118c449e"
  workspaces: [926872]
calendar:
  personal-holidays:
    url: https://calendar.google.com/calendar/ical/path-to-privat-ical/basic.ics
    refresh: 86400
    type: 0
  business-holidays:
    url: http://www.ifeiertage.de/by-.ics
    refresh: 7776000
    type: 1
