doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "toggl_01"
    password: "6:I&4LdF"
    dbname: "toggl_01"
    host: "localhost"
common:
  timezone: "Europe/Berlin"
  working_days: [1, 2, 3, 4, 5]
  working_hours_per_day: 8
  start_weekday: 1
  rate: 84
system:
  token: system
  name: Allgemein
  working_days: 62
  costs:
    monthly:
      rent: 1523
      telecom: 70
      kindergarden: 25
      wages: 120
      cleaning: 102
      energy: 198
      coffee: 78
    quarterly:
      xing: 20
      igeko: 100
    yearly:
      radio: 140
      companyinsurance: 1000
      carinsurance1: 623
      yellowpages: 77
      ihk: 150
      t3n: 35
      accountingsoftware: 200
      bundesanzeiger: 30
      cartax: 264
general:
  locale: de_DE
toggl:
  apiKey: "e1d49a86954369425dd936a4b39aac87"
  workspaces: [986852]
calendar:
  personal-holidays:
    url: https://calendar.google.com/calendar/ical/rsvo3pko3vd0g9ta29jkr8q9is%40group.calendar.google.com/private-7e2614ba26b46d0e67c8fd49c346ca6d/basic.ics
    refresh: 86400
    type: 0
    excused: [krank,krankheit,arzt,entschuldigt]
  business-holidays:
    url: http://i.cal.to/ical/65/bayern/feiertage/e15a0975.8ed5c461-47fa1761.ics
    refresh: 7776000
    type: 1
