doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "toggl_01"
    password: "6:I&4LdF"
    dbname: "toggl_01"
    host: "localhost"
user:
  joschi:
    holidays_per_year: 28
    costs: 2855
  isabel:
    aliases: [isi]
    working_days: [2, 3, 4, 5]
    holidays_per_year: 25
    costs: 1007
  nina:
    working_hours_per_day: 6.5
    holidays_per_year: 21
    costs: 1462
  klaus:
    holidays_per_year: 26
    costs: 3283
  bertram:
    working_days: [1, 2, 3]
    holidays_per_year: 16
    costs: 1666
  jule:
    holidays_per_year: 25
    costs: 3022
  system:
    costs: 5000
common:
  timezone: "Europe/Berlin"
  working_days: [1, 2, 3, 4, 5]
  working_hours_per_day: 8
  start_weekday: 1
  rate: 84
system:
  token: system
  name: Allgemein
general:
  locale: de_DE
toggl:
  apiKey: "e1d49a86954369425dd936a4b39aac87"
  workspaces: [986852]
calendar:
  personal-holidays:
    url: https://calendar.google.com/calendar/ical/rsvo3pko3vd0g9ta29jkr8q9is%40group.calendar.google.com/private-7e2614ba26b46d0e67c8fd49c346ca6d/basic.ics
    refresh: 86400
    type: 0
  business-holidays:
    url: http://i.cal.to/ical/65/bayern/feiertage/e15a0975.8ed5c461-47fa1761.ics
    refresh: 7776000
    type: 1
