doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "username"
    password: "password"
    dbname: "database"
    host: "localhost"
user:
  john:
    holidays_per_year: 28
    personnel_costs: 2500
  jane:
    aliases: [nick]
    working_days: [1, 2, 3, 4]
    working_hours_per_day: 6
    holidays_per_year: 24
    personnel_costs: 2400
general:
  timezone: "Europe/Berlin"
  working_days: [1, 2, 3, 4, 5]
  working_hours_per_day: 8
toggl:
  apiKey: "8ebaedbfb2b5724cb537fdb5118c449e"
  workspaces: [926872]
calendar:
  personal_holidays:
    url: https://calendar.google.com/calendar/ical/path-to-privat-ical/basic.ics
    refresh: 86400
    type: 0
  business_holidays:
    url: http://www.ifeiertage.de/by-.ics
    refresh: 7776000
    type: 1
