doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "username"
    password: "password"
    dbname: "database"
    host: "localhost"
common:
  timezone: "Europe/Berlin"
  working_days: [1, 2, 3, 4, 5]
  working_hours_per_day: 8
  start_weekday: 1
  rate: 60
system:
  token: system
  name: Allgemein
  costs:
    rent: 1000
    telecom: 100
toggl:
  apiKey: "8ebaedbfb2b5724cb537fdb5118c449e"
  workspaces: [926872]
calendar:
  personal_holidays:
    url: https://calendar.google.com/calendar/ical/path-to-privat-ical/basic.ics
    refresh: 86400
    type: 0
    excused: [ill,sick,doctor]
  business_holidays:
    url: http://www.ifeiertage.de/by-.ics
    refresh: 7776000
    type: 1
